# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j2lte/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j2lte

PRODUCT_COPY_FILES += \
    vendor/samsung/j2lte/proprietary/lib/hw/camera.exynos3.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.exynos5.so \
    vendor/samsung/j2lte/proprietary/lib/hw/sensors.universal3475.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.universal3475.so \
    vendor/samsung/j2lte/proprietary/lib/libexynoscameraexternal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscameraexternal.so \
    vendor/samsung/j2lte/proprietary/vendor/bin/cbd:$(TARGET_COPY_OUT_VENDOR)/bin/cbd \
    vendor/samsung/j2lte/proprietary/vendor/firmware/fimc_is_fd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fd.bin \
    vendor/samsung/j2lte/proprietary/vendor/firmware/fimc_is_lib_isp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib_isp.bin \
    vendor/samsung/j2lte/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin
