# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/on5ltetmo/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/on5ltetmo

PRODUCT_COPY_FILES += \
    vendor/samsung/on5ltetmo/proprietary/etc/firmware/audience-es804-data.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/audience-es804-data.bin \
    vendor/samsung/on5ltetmo/proprietary/etc/firmware/audience-es804-fw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/audience-es804-fw.bin \
    vendor/samsung/on5ltetmo/proprietary/lib/hw/camera.exynos3.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.exynos5.so \
    vendor/samsung/on5ltetmo/proprietary/lib/hw/sensors.universal3475.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.universal3475.so
